// Copyright 2019 Ian Maines
#include "pch.h"
#include <iostream>

#include <vector>
#include <cstdint>

/* https://projecteuler.net/problem=2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/


int main()
	{
	// Initialization case, first two numbers are 1
	uint32_t prev = 0;
	uint32_t current = 1;

	uint64_t sum = 0;

	while (current < 4'000'000)
		{
		// Math portion of the loop
		if (current % 2 == 0)
			{
			sum+=current;
			}

		// Update
		auto temp_current = current;
		current=current+prev;
		prev = temp_current;
		}

	std::cout << "Answer: " << sum << std::endl;

	}
